### ISSUE TITLE
Potential Memory Leak Issue

### ISSUE THREAD

**Issue by janszedc** [dataplat/dbatools#8035] opened 2021-12-23 14:44 UTC
### Verified issue does not already exist?

Yes

### What error did you receive?

I am not receiving an error, but my memory will quickly (or sometimes slowly over many hours) go to 100% when using DBATools in unison with Powershell Universal.

![image](https://user-images.githubusercontent.com/49908138/147255916-ba4398fa-4681-43d9-9469-ecc1eb1e1f8c.png)

In the image above, my memory is not spiked, but you can clearly see the services that are consuming the most memory. The pwsh session is my dashboard, which is a .NET Core REACT based site utilizing DBATools to populate the data of the frontend.

### Steps to Reproduce

The only command I am using are Invoke-DbaQuery, Connect-DBAInstance, and Write-ToDbaDataTable.

### Are you running the latest release?

Yes

### Other details or mentions

I am using a service called Powershell Universal, that uses pwsh.exe to run dasbhoard and also scripts. Other users have reported issues when using DBATools and it may have something to do with the logging of DBATools.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Dec 23, 2021 9:42 AM  
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2012 (SP4) (KB4018073) - 11.0.7001.0 (X64)   Aug 15 2017 10:23:29   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

Microsoft SQL Server 2017 (RTM-CU26) (KB5005226) - 14.0.3411.3 (X64)   Aug 24 2021 09:59:15   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.3875.0

**Comment by psott** [comment] 2021-12-23 17:33
I'm also affected. My dashboard heavily relies on dbatools (99% Invoke-DbaQuery and 
Write-DbaDbTableData) .Current workaround is to restart the PU service every night.

Is it possible to disable dbatools logging? At least to check if it is the cause?

**Comment by potatoqualitee** [comment] 2021-12-24 21:20
Thanks for the feedback, everyone. @adamdriscoll i saw that you did some debugging and discovered that our logging wasn't releasing memory. Can you share that here so I can share @FriedrichWeinmann who created our logging?

@psott sorry you're having to restart each night. I believe you can disable logging with:

```
Set-DbatoolsConfig -FullName logging.errorlogenabled -Value $false | Register-DbatoolsConfig
Set-DbatoolsConfig -FullName logging.errorlogfileenabled-Value $false | Register-DbatoolsConfig
Set-DbatoolsConfig -FullName logging.messagelogenabled-Value $false | Register-DbatoolsConfig
Set-DbatoolsConfig -FullName logging.messagelogfileenabled-Value $false | Register-DbatoolsConfig
```

**Comment by wsmelton** [comment] 2022-01-03 16:06
Our logging lives for the duration of the PowerShell session in order to capture and process the messages each command may fire.

If in UD the pwsh.exe process lives forever then I'd say the proper fix for this would be to disable our logging for your sessions.

**Comment by FriedrichWeinmann** [comment] 2022-01-03 16:47
Found the issue and fixed it in #8048 .
Due to forgetting to handle a boolean output value in the logging it would very, very slowly accumulate. Run that long enough and you have memory issues 😅

**Comment by potatoqualitee** [comment] 2022-01-03 18:23
HELLLL YEAHHHH! Sweet as hell. i was just gonna throw in a bunch of garbage collections 🤣 . Thanks so much @FriedrichWeinmann!

**Comment by wsmelton** [comment] 2022-01-03 19:06
Might not hurt to make that a big notice on the release that it fixes this memory leak issue @potatoqualitee

**Comment by janszedc** [comment] 2022-01-04 12:10
@FriedrichWeinmann  @potatoqualitee Been running my Powershell Universal dashboard (service) all night and overall memory on my box has been capped at 70%. Newest version of DBATools seems to have fixed the problem. Thank you for your help!

**Comment by FriedrichWeinmann** [comment] 2022-01-04 16:16
Excellent and thank you for confirming.
And happy to help ... after all, I'm the criminal that implemented the bug to begin with ;)

**Comment by janszedc** [comment] 2022-01-04 20:23
@FriedrichWeinmann perhaps I spoke to soon as I have been testing all day and will randomly see memory spike to 99% fairly quickly. It is difficult to say if this is DBATools related at this point or Powershell Universal. Something is still not releasing memory. @psott Have you been able to test on your end with the DBATools 1.1.48?

**Comment by adamdriscoll** [comment] 2022-01-04 20:41
If you are able, feel free to take a memory dump of the PSU process and I can analyze it and let you know what's using the memory. I can share a dropbox folder that you can drop the file in since it will be very large. Zipping the file will compress it significantly.

**Comment by janszedc** [comment] 2022-01-04 23:16
> If you are able, feel free to take a memory dump of the PSU process and I can analyze it and let you know what's using the memory. I can share a dropbox folder that you can drop the file in since it will be very large. Zipping the file will compress it significantly.

I can do that first thing tomorrow morning. Shoot me a link to the Dropbox once created. Also, do you want a dump file of the service itself or the pwsh.exe it spins up for the dashboard? Or both?

**Comment by adamdriscoll** [comment] 2022-01-04 23:18
Both would probably be handy. I'll need an email address to share the dropbox link with. You can email me at adam[at]ironmansoftware.com.

**Comment by janszedc** [comment] 2022-01-04 23:18
> Both would probably be handy. I'll need an email address to share the dropbox link with. You can email me at adam[at]ironmansoftware.com.

Sending now. Thanks

**Comment by adamdriscoll** [comment] 2022-01-05 17:23
Here's what I'm seeing in the dump. There is a static variable that is maintaining a dictionary that contains script blocks. We might need to look at the `ConfigurationHost.Validation` variable and dispose of unused scriptblocks. 

![image](https://user-images.githubusercontent.com/1256531/148260696-254b306e-2766-45d6-b060-936ba293431c.png)

Those script blocks reference an execution console that is responsible for much of the memory usage. 

![image](https://user-images.githubusercontent.com/1256531/148260787-c3531df0-e1ec-4fe2-96fc-a79a2f7df154.png)

There are still quite a few log entries as well.

![image](https://user-images.githubusercontent.com/1256531/148260934-8068cf22-fca9-436e-941f-2b7021392c45.png)

**Comment by adamdriscoll** [comment] 2022-01-05 17:24
There are also 200 dictionaries each with 39,900 items in them. 

![image](https://user-images.githubusercontent.com/1256531/148261236-ff1865fc-79ab-4c21-b4df-7ae0d66440e9.png)

**Comment by FriedrichWeinmann** [comment] 2022-01-05 19:02
Thank you very much for processing that.
We keep - by default - 1024 LogEntry items in memory, but there is no reason for the callstack to be that size. Going to fix that without loss of functionality from a logging/debugging perspective.
The scriptblocks are a bit more of an interesting matter, as they should theoretically all point at the internal session state of the main runspace (which would be open anyway). Got ideas on things to try out, but this one may need a few test iterations.

Looking into both as soon as possible.

**Comment by FriedrichWeinmann** [comment] 2022-01-08 09:12
Alright, next version that should at least resolve Adam's findings in #8062

**Comment by potatoqualitee** [comment] 2022-01-11 13:13
Hey @janszedc  - sorry that was an autoclose. Release 1.1.50 is what you're looking for, as it has Fred's most recent changes.

**Comment by potatoqualitee** [comment] 2022-01-11 13:14
I'll keep this open until we receive confirmation that the changes work.

**Comment by janszedc** [comment] 2022-01-11 13:48
@adamdriscoll It looks like this has to do with defining endpoints/schedules within the dashboard page itself (above the content). I managed to capture this image after saving/auto-deploying my dashboard code several times and you can see all the powershell sessions: 
![image](https://user-images.githubusercontent.com/49908138/148954135-7ee9e22e-9939-48b5-84f1-4bde7e58c594.png)

As soon as I commented out the endpoints and went back to schedules -> scripts -> invoke API the problem appears to be resolved, but of course I am still testing. Here is an example of the endpoint defined in the dashboard:
```
$SyncDBAOPDashboard = New-UDEndpointSchedule -Every 60 -Second
New-UDEndpoint -Schedule $SyncDBAOPDashboard -Endpoint {
    Invoke-RestMethod 'myServer:5001/SyncDBAOPDashboard'
} | Out-Null
```

**Comment by janszedc** [comment] 2022-01-11 14:58
> Hey @janszedc - sorry that was an autoclose. Release 1.1.50 is what you're looking for, as it has Fred's most recent changes.

No problem. Just updated to 1.1.50 and am testing now.

**Comment by janszedc** [comment] 2022-01-13 15:34
I have been closely monitoring memory consumption and while I am not seeing any rapid spikes, I am still noticing memory very slowly creeping closer to 100% as the day goes on. I restarted my service this morning so memory could be released and will watch again to see what it looks like a few hours from now. Currently using version 1.1.50.

**Comment by janszedc** [comment] 2022-01-13 16:36
@potatoqualitee I actually set all my variables to $NULL after they have been used and run garbage collection afterwards. I can add `[System.Gc]::Collect()` as well though.

```
$NonProdData = $Null
$ProdData = $Null
 [gc]::Collect()
```

**Comment by potatoqualitee** [comment] 2022-01-13 16:41
@janszedc i recall there being potential scoping issues, like maybe it has to be our commands and not yours. but! try adding that garbage collection command 3 times. i dont know why it takes 3, but that's been my experience

**Comment by janszedc** [comment] 2022-01-17 14:45
@potatoqualitee I added more GC statements last week, but still saw the memory leak issue this morning so I decided to "clutter" up my dashboard by adding them everywhere and it caused a lot of NULL REFERENCE EXCEPTIONS =[ ... although to be fair I did not see the issue go away. I will keep messing with it on my end though.

**Comment by potatoqualitee** [comment] 2022-01-17 18:45
interesting that there are downsides! that does point to it being us in our runtime.

**Comment by janszedc** [comment] 2022-01-20 15:31
This only occurs when a user (myself) has the dashboard/webpage open. Even if it is running, I don't notice any memory leak issues. If I leave the webpage open and do not touch it, memory rises slowly.. but as soon as I start clicking around which causes refreshes I can see memory start to spike fast. At this point I have gotten rid of all garbage collection commands as I did not notice any improvement. Any other recommendations that I can test?

**Comment by potatoqualitee** [comment] 2022-01-20 15:44
Hmmm seeing this, @FriedrichWeinmann and @adamdriscoll would yall say it's in UD, then?

**Comment by janszedc** [comment] 2022-01-26 18:12
Commenting for visibility as I am still experiencing this issue. Any help or ideas on what I can try is much appreciated =]

**Comment by wsmelton** [comment] 2022-01-27 13:11
Have you tried disabling our logging? Running from the dashboard it won't server much purpose.

**Comment by janszedc** [comment] 2022-01-31 13:13
@adamdriscoll When I take the same script and run it in a while loop locally on the same box hosting PSU, I do not see the memory leak whatsoever. It seems there are memory leak issues related to both the dashboards piece of PSU and the Scripts/Scheduling component of PSU. Anything else I can do on my end to help track this down?

**Comment by adamdriscoll** [comment] 2022-01-31 16:19
@janszedc  - I opened a new issue on the PSU issue repo to track this since it's related to PSU. I think I will have to do some additional debugging on my end to see what's causing this issue in PSU. It's likely has to do runspace management in PSU. I have some ideas and will let you know next steps.

**Comment by janszedc** [comment] 2022-01-31 16:27
@adamdriscoll Based on my research I was thinking the same regarding runspaces. At this point I've covered my scripts in explicit GC statements, $null'd out variables, and disabled DBA Tools logging so it must have something to do with runspaces not releasing memory properly. Thanks for looking into this!

**Closed** 2022-01-31 16:27 UTC
Labels: bugs life, triage required
