### ISSUE TITLE
dbatools errors on SSH with pwsh 7.3

### ISSUE THREAD

**Issue by savornicesei** [dataplat/dbatools#8657] opened 2022-11-21 08:57 UTC
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

```
PSMessageDetails      : 
Exception             : System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling "Invoke"
 with "3" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not import /home/***/.local/share/powershell/Modules/dbatools/1.1.95/bin/smo/coreclr/Microsoft.SqlSer
ver.XEvent.Linq.dll : 
                         144 |                   
   [Reflection.Assembly]::LoadFrom($assemblyPath)
                             |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                             | Exception calling "LoadFrom" with "1" argument(s): "Could not load file
    
                         | or assembly
                             | '/home/***/.local/share/powershell/Modules/dbatools/1.1.95/bin/smo/coreclr/Microsoft.SqlServer.XEvent.Linq.dll'. An attempt was made to load a program with an incorrect format. "
  

```

### Steps to Reproduce

I have a powershell script that uses dbatools to create a db and run some update scripts ( only uses `Test-DbaConnection`, `New-DbaDatabase`, `Invoke-DbaQuery` ). 
This script is run on an Amazon Linux 2 machine through powershell SSH

```powershell
Invoke-Command -Session $ssh -ScriptBlock { }  -AsJob -ArgumentList ( ...)
```
With powershell core 7.2.x  (64-bit) it works fine, no matter the dbatools versions. With powershell core 7.3 (64-bit) I get that ugly error, no matter the dbaversion.
The powershell packages were installed from official https://packages.microsoft.com/rhel/7/prod/ repo.
Running the script directly on the machine worked - might be an upstream issue (this one sounds promising https://github.com/PowerShell/PowerShell/issues/18587 )

### Please confirm that you are running the most recent version of dbatools

Yes.

### Other details or mentions

Might be related to  #8638 

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

7.2.7, x86_64
and 
7.3.0, x86_64

### SQL Server Edition and Build number

SQL Server 2016

### .NET Framework Version

none

**Comment by mattcargile** [comment] 2022-11-21 22:30
Looks like it is related to the Issue #8195 which has a PR in for it. Maybe there is another assembly that is mistakenly loaded from the _GAC_.

**Comment by savornicesei** [comment] 2022-11-22 07:03
Hi @mattcargile 
That was fixed in July and it does not explain why it works with PS 7.2.x and not with PS 7.3
Is there something I can do to help investigate this issue?

Thanks,
Simo

**Comment by mattcargile** [comment] 2022-11-22 07:06
Right. I assume it is something with the ordering of the dll loads. In the past I have opened a remoting session and inspected the process on the remote with a tool like `procexp` to see where the dlls are loading from.

**Comment by wsmelton** [comment] 2022-11-23 15:46
Everyone should be aware when upgrading PowerShell that its release are inline with .NET releases. PowerShell 7.3 bumped to .NET 7 while PowerShell 7.2 is on .NET 6. There can be many considering our module is dependent upon SMO that can be affected by that change to the underlying framework.

This could be with DLL loading or the fact some of our SMO library is out of date and needs to be updated to a release supporting .NET 7 runtime.

**Comment by wsmelton** [comment] 2022-11-23 15:47
Until the module is tested under the new release it should be assumed there will be issues in various areas. The initial release of PS 7.3 caused Az modules to break, Azure team had to release a fix for that just like we may have to things identified.

**Comment by savornicesei** [comment] 2022-11-23 16:12
@wsmelton That makes sense. I did not know PS7.3 targets .NET 7 - quite a bald move for a minor release, IMHO

**Comment by wsmelton** [comment] 2022-11-23 17:59
It is part of [PowerShell 7 release structure](https://devblogs.microsoft.com/powershell/powershell-7-1-team-investments-and-preview-1-release) as PowerShell 7+ is going to line up with the .NET release pipeline as well.

**Comment by wsmelton** [comment] 2023-01-08 23:46
@savornicesei you stated you were using the latest release of the module but the output you provided does not show that you are running 1.1.143 release.

```console
PSMessageDetails      : 
Exception             : ...
 with "3" argument(s): "Could not import /home/.local/share/powershell/Modules/dbatools/**1.1.95**/... 
```

Please perform your test using 1.1.143. If the issue still exists we can reopen this issue.

**Comment by savornicesei** [comment] 2023-01-10 10:05
@wsmelton Indeed, that's because both versions of dbatools fail due to powershell 7.3.

I rechecked it today with powershell 7.3 and dbatools 1.1.143
```
##[error]Could not import /home/***/.local/share/powershell/Modules/dbatools/1.1.143/bin/smo/coreclr/Microsoft.SqlServer.XE.Core.dll : 
MethodInvocationException: /home/***/.local/share/powershell/Modules/dbatools/1.1.143/internal/scripts/libraryimport.ps
##[error]1:150
Line |
 150 |                      [Reflection.Assembly]::LoadFrom($assemblyPath)
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "LoadFrom" with "1" argument(s): "Could not load file
     | or asse
##[error]mbly
     | '/home/***/.local/share/powershell/Modules/dbatools/1.1.143/bin/smo/coreclr/Microsoft.SqlServer.XE.Core.dll'. An attempt was made to load a program with an incorrect format. "


##[error]Could not import /home/***/.local/share/powershell/Modules/dbatools/1.1.143/bin/smo/coreclr/Microsoft.SqlServer.XEvent.Linq.dll : 
MethodInvocationException: /home/***/.local/share/powershell/Modules/dbatools/1.1.143/internal/scripts/libraryimpor
##[error]t.ps1:150
Line |
 150 |                      [Reflection.Assembly]::LoadFrom($assemblyPath)
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "LoadFrom" with "1" argument(s): "Could not load file
     | or 
##[error]assembly
     | '/home/***/.local/share/powershell/Modules/dbatools/1.1.143/bin/smo/coreclr/Microsoft.SqlServer.XEvent.Linq.dll'. An attempt was made to load a program with an incorrect format. "
```

Best,
Simo

**Comment by potatoqualitee** [comment] 2023-01-11 14:53
dbatools 2.0 will work on PWSH 7.2+ including 7.3 👍🏼

**Comment by wsmelton** [comment] 2023-01-11 16:04
This isn't a matter of it working on those versions it is with it working through a PS Remoting session through ssh.

PS 7.4 is released in preview. Can you test on that @savornicesei I'm curious to see if the same issue is there?

**Comment by potatoqualitee** [comment] 2023-01-11 17:33
ohh isnt this the problem that i have no idea how to fix other than to suggest the end-user setup a pwsh7 remoting profile default?

**Comment by wsmelton** [comment] 2023-01-11 18:20
This is remoting to a Linux machine from PowerShell 7 via SSH with `New-PSSession .. -Username` (has OpenSSH client installed). From there running dbatools scripts, so our module installed on RHEL and via PS Remote SSH session.

**Comment by briantist** [comment] 2023-02-26 16:46
This problem is trivially reproducible without remoting, see:
https://github.com/lowlydba/lowlydba.sqlserver/pull/175#issuecomment-1445189474

**Comment by wsmelton** [comment] 2023-02-26 16:57
We will not be backporting fixes for the library issues so if 2.0 fixes this please let us know. The preview/beta release of 2.0 is available on PS Gallery.

**Comment by briantist** [comment] 2023-02-26 17:07
@wsmelton 2.0 does work
https://github.com/lowlydba/lowlydba.sqlserver/pull/175#issuecomment-1445380088

**Comment by savornicesei** [comment] 2023-03-14 06:08
Tested with pwsh 7.3.3 and dbatools 1.1.143. I still get the same error
```
##[error]Could not import /home/***/.local/share/powershell/Modules/dbatools/1.1.143/bin/smo/coreclr/Microsoft.SqlServer.XE.Core.dll : 
MethodInvocationException: /home/***/.local/share/powershell/Modules/dbatools/1.1.143/internal/scripts/libraryimport.ps
##[error]1:150
Line |
 150 |                      [Reflection.Assembly]::LoadFrom($assemblyPath)
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "LoadFrom" with "1" argument(s): "Could not load file
     | or asse
##[error]mbly
     | '/home/***/.local/share/powershell/Modules/dbatools/1.1.143/bin/smo/coreclr/Microsoft.SqlServer.XE.Core.dll'. An attempt was made to load a program with an incorrect format. "


##[error]Could not import /home/***/.local/share/powershell/Modules/dbatools/1.1.143/bin/smo/coreclr/Microsoft.SqlServer.XEvent.Linq.dll : 
MethodInvocationException: /home/***/.local/share/powershell/Modules/dbatools/1.1.143/internal/scripts/libraryimpor
##[error]t.ps1:150
Line |
 150 |                      [Reflection.Assembly]::LoadFrom($assemblyPath)
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "LoadFrom" with "1" argument(s): "Could not load file
     | or 
##[error]assembly
     | '/home/***/.local/share/powershell/Modules/dbatools/1.1.143/bin/smo/coreclr/Microsoft.SqlServer.XEvent.Linq.dll'. An attempt was made to load a program with an incorrect format. "
```

**Comment by wsmelton** [comment] 2023-03-14 11:59
@savornicesei that version will always have the issue as we are not back porting the fix.

Please try v2.0 pre-release from the PS Gallery. Reports are showing that it doesn't have the issue.

**Closed** 2023-03-14 12:00 UTC
Labels: bugs life, ps core, fix in 2.0
