### ISSUE TITLE
Please add a switch to prevent loading XEvent libraries

### ISSUE THREAD

**Issue by TrevorW7** [dataplat/dbatools#8688] opened 2022-12-14 21:32 UTC
### Summarize Command's Functionality

Please, add a switch that prevents loading XEvent modules when importing dbatools.

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

I use a product called PowerShell Universal. The XEvent libraries have a problem loading similar to ARM and/or CI/CD. Essentially, it crashes the import.

Within this file: C:\Program Files\PowerShell\Modules\dbatools\1.1.143\internal\scripts\libraryimport.ps1, at line 100 is:
`     # XEvent stuff kills CI/CD
    if ($PSVersionTable.OS -match "ARM64") {
        $names = $names | Where-Object { $PSItem -notmatch "XE" }
    } 
`
That code prevents loading XEvent modules if the OS is ARM64 (removes their dll names). 
Can you add a switch for importing dbatools such that none of the XE dlls are loaded when the switch is applied? 
Perhaps, -NoXEventModules

If you don't make the change, I will have to manually update that file with every update. Would much prefer a switch so its not an issue going forward.

**Comment by wsmelton** [comment] 2022-12-19 14:07
@TrevorW7 we are restructuring the codebase in release 2.0. The library and SMO are now packaged in a separate module [dataplat/dbatools.library](https://github.com/dataplat/dbatools.library) so that library import script will likely have less use after we are done.

This seems like it would be a duplicate of #7789 which will be addressed in 2.0 release.

**Comment by TrevorW7** [comment] 2022-12-21 14:10
I would rather not tie the issue to another specific product. The setup I am using with PSU is complicated: it uses a SQL DB backend, GITLab/Version control, CyberArk, multiple nodes, etc. 

In this case, I think its best to simply support not requiring the XEvent dlls to load.  Setting up PSU as we are using it would not be easy. 

NOTE: I am 100% certain, dbatools works fine with PSU, as we have it configured, when the "XE" dlls do not load (I manually removed the if condition at line 100 in libraryimport.ps1. That made sure the XE dlls never loaded. Problem was resolved. The change is not impacting the functionality of dbatools we are using.

The suggested solution works great for me. Without it, I would have to manually change libraryimport.ps1 every time we install a newer version.

**Comment by wsmelton** [comment] 2022-12-21 16:05
If I recall PSU loads the modules into a custom host @potatoqualitee the environmental configuration of the product itself has little affect.

**Comment by TrevorW7** [comment] 2022-12-21 16:12
DBATOOLS was working with PSU until we setup the more complex configuration. At some point, I would be happy to dig into it to find out why it cant load those DLLs in the complex setup, but as far as I can tell, we don't need the SMO libraries. If it is already planned to separate the SMO libraries, that works for me. 

NOTE: I am working with Adam @ PSU for multiple improvements that we deem critical. In my priority list, I would take manually removing the DLLs until the current priorities are addressed. Its likely a month before I would be ready.

**Comment by potatoqualitee** [comment] 2022-12-30 07:32
I'm also working with adam and want to ensure that dbatools works well with each environment. I tried to spin up a container but the PSU container version of PS (7.1) is too old for dbatools in pwsh (7.2+), so he will be updating that shortly. 

It is strange that it breaks only sometimes. do you recall what you changed that made it go from working to broken? The reason im asking is bc i want to add a regression test to our new setup to ensure it works each time we update our library, i beleive you are the second person that ran into this issue. The new dbatools 2.0 will have the library separate but it's 100% reliant on SMO -- this time, however, they are newer libraries and loaded differently. If you're looking for a non-SMO solution, Invoke-SqlCmd2 is pretty very nice.

**Comment by potatoqualitee** [comment] 2023-01-27 13:07
I will not be adding a switch, as I'd like to make it actually work. If I can get some insight on how to repro, I can ensure it works.

**Comment by TrevorW7** [comment] 2023-01-27 13:45
I am not sure what changed that caused the issue. Our environment is complex with lots of compliance and many aspects of configuration pushed down. As noted, we are using PSU with a separate SQL server and GITLAB, with multiple nodes, such that production changes only come from the pipeline in GITLAB. We are standing up multiple implementations/twins of the exact same setup, so I will be able to do is see if the issue shows up/is reproduced in the the new separate environment. 

As part of the process, we will be documenting, step by step, our installation. Some aspects cannot be shared but they are not likely the source of the problem. For example, we use CyberArk to store credentials and use the CA API to pull credentials from a vault such that only the service account running on specific servers can access the vault's credentials. That doesn't affect the core setup, only the code that uses the credentials. 

I already plan on having a public-friendly version of the installation., but it will be  a while before its complete. Willing to share when ready. Willing to simply to work with Adam to try and identify exactly what triggers the problem.

**Comment by TrevorW7** [comment] 2023-02-09 19:25
So, I think I am getting closer to the problem. When I disable SMO, i generally don't have issues, but with it disabled, I am now finding that I can get this error: 

Method not found: Void Microsoft.Data.SqlClient.SqlConnectionStringBulder.set_Encrypt(Boolean)

This seems to be related to using a Domain account/Integrated Security rather than a native SQL account. Haven;t proven that yet, but working on it. So, under some contexts (I.e. spawning a separate runspace), the SMO dlls won't load and it crashes DBATOOLS. Disabling the SMO modules allows the rest of the modules to load within a separate runspace, but in some separate runspaces, the domain account seems to trigger the error I listed above. I think the SMO module(s) are needed to pass the integrated credential (again guessing based on other incidents of this error)

I am reaching out to Adam to see if we can narrow this down. At the moment, I am just guessing. So, I am hoping to work with Adam to create a reproduceable example that can be shared.

**Comment by wsmelton** [comment] 2023-02-09 20:02
What do you mean by "disable SMO"?

Are you disabling the SMO files we ship in the module?
Are you disabling SMO that may live on the host (GAC)?

**Comment by wsmelton** [comment] 2023-02-09 20:08
If you disable SMO in the module (meaning you prevent our import process from loading the library path), that will cause PowerShell (aka .NET/dotnet) to default to the GAC in Windows. This is whether you are running Windows PowerShell or PowerShell 7.

The Connect command in our module now uses `Microsoft.Data.SqlClient`. This **is not** shipped in Windows Server/Desktop so unless Adam installs on that on his container image it will not be found, and will cause the command to fail whenever it calls a namespace that is not found since that library didn't get loaded.

**Comment by TrevorW7** [comment] 2023-02-09 20:40
Very sorry, I had SMO on the brain, but really meant the XEvent libraries (my first comment is what I disabled). So, I set it back and let the XEvent libraries load but I still get the same result. 

Method not found: Void Microsoft.Data.SqlClient.SqlConnectionStringBulder.set_Encrypt(Boolean)

I'm still trying to figure this out. I created a separate dashboard in PSU, added a page, and created a simple test that works (runs the query just fine). Its failing where I have a fairly complex data grid. Again, I am reaching out to Adam and will come back when I think I have something ready or Adam helps me resolve it separately and if that happens I will update my post here promptly. Maybe some feature I use is changing the underlying libraries available to PSU or there is just some weird glitch. 

Thank you for the prompt response. Its appreciated.

**Comment by wsmelton** [comment] 2023-02-09 20:49
Can you test against the beta release?

```powershell
Install-Module dbatools.library -RequiredVersion '2023.1.29'
Install-Module dbatools -AllowPrerelease -RequiredVersion '2.0.0-preview1'
```

**Comment by potatoqualitee** [comment] 2023-03-04 09:44
Please test with the beta and let us know

**Comment by potatoqualitee** [comment] 2023-03-04 17:57
I added an arm64 runner to ensure stuff works. XE commands run well. 
https://github.com/dataplat/dbatools/pull/8788

**Closed by potatoqualitee** 2023-03-04 17:57 UTC
Labels: feature, fix in 2.0
