### ISSUE TITLE
issue with Invoke-DbaQuery wit dbatools 2.0.3

### ISSUE THREAD

**Issue by ESLFHVI** [dataplat/dbatools#8950] opened 2023-06-05 08:56 UTC
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

I've got an issue when I launch the `Invoke-DbaQuery` command.

```
Invoke-DbaQuery: Invoke-DbaQuery -SqlInstance $sqlinstance -Database master -Query " "SELECT SERVERPROPERTY('productversion')"  : WARNING: [10:59:37][Invoke-DbaQuery] [INSTANCE] Failed during execution | Cannot convert the "System.Data.SqlClient.SqlConnection" value of type "System.Data.SqlClient.SqlConnection" to
type "Microsoft.Data.SqlClient.SqlConnection".


19 réponses
```

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
 Invoke-DbaQuery -SqlInstance $sqlinstance -Database master -Query " "SELECT SERVERPROPERTY('productversion')"

### Please confirm that you are running the most recent version of dbatools

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      3      -1
```

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.5582
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.5582
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
### SQL Server Edition and Build number
```
Microsoft SQL Server 2022 (RTM-CU3) (KB5024396) - 16.0.4025.1 (X64)   Mar 13 2023 19:10:08   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 


Microsoft SQL Server 2019 (RTM-CU19) (KB5023049) - 15.0.4298.1 (X64)   Jan 27 2023 16:44:09   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
```

### .NET Framework Version

```
PSChildName Version
----------- -------
Client      4.8.03761
Full        4.8.03761
Client      4.0.0.0
```

**Comment by wsmelton** [comment] 2023-06-05 13:06
I'm not able to replicate that warning/error:

```console
C:\> C:\tmp\init.ps1
[+] Running 3/3
 - Container sql2019  Healthy
 - Container sql2022  Healthy
 - Container sql2017  Healthy
Successful connection established to: localhost,1417
Successful connection established to: localhost,1419
Successful connection established to: localhost,1406
C:\> Invoke-DbaQuery -SqlInstance $sqlCn19 -Database master -Query "SELECT SERVERPROPERTY('productversion')"

Column1
-------
15.0.4312.2


C:\> Invoke-DbaQuery -SqlInstance $sqlCn22 -Database master -Query "SELECT SERVERPROPERTY('productversion')"

Column1
-------
16.0.4003.1


C:\> Get-Module dbatools

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.3      dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener...}
```

Is it possible you have other modules or multiple versions of dbatools on your device? Possible duplicate of #8894.

**Comment by mattcargile** [comment] 2023-06-10 20:04
It appears to be related to the _SqlServer_ module on version _5.1_. I was able to get this re-proed with the below.

```powershell
ipmo SqlServer
ipmo dbatools
set-dbatoolsInsecureConnection -sessionOnly # this isn't relevant to the fix
Invoke-DbaQuery -SqlInstance $sqli -Database master -Query " SELECT SERVERPROPERTY('productversion')"
 ```

I got

```powershell
WARNING: [15:01:27][Invoke-DbaQuery] [sqli] Failed during execution | Cannot convert the "System.Data.SqlClient.SqlConnection" value of type
"System.Data.SqlClient.SqlConnection" to type "Microsoft.Data.SqlClient.SqlConnection".
```

Workaround would be to `ipmo dbatools` first inside your session.

**Comment by mc6114** [comment] 2023-06-14 18:19
I am having this same issue. dbatools 2.0.4 on version 5.1. 

I'm not following the workaround.

**Comment by mattcargile** [comment] 2023-06-15 16:03
> I am having this same issue. dbatools 2.0.4 on version 5.1. 
> 
> 
> 
> I'm not following the workaround. 

As far as I know the workaround is the only way to resolve.

**Comment by mc6114** [comment] 2023-06-15 18:34
> As far as I know the workaround is the only way to resolve.

What is the work around? 
Is it import-module dbatools?

**Comment by mattcargile** [comment] 2023-06-15 20:27
> 
> 
> > As far as I know the workaround is the only way to resolve.
> 
> 
> 
> What is the work around? 
> 
> Is it import-module dbatools? 

Are you using the `SqlServer` module? If so, the solution is to import `dbatools` first. Otherwise, you might have another issue.

**Comment by andreasjordan** [comment] 2023-06-26 08:40
Will close this now, but can reopen if needed.

**Closed by andreasjordan** 2023-06-26 08:40 UTC
Labels: bugs life, pending OP feedback
