### ISSUE TITLE
None of the commands are working

### ISSUE THREAD

**Issue by jyoukhanis** [dataplat/dbatools#9412] opened 2024-06-27 17:40 UTC
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

The network path was not found!
![17195095969497216113368363732624](https://github.com/dataplat/dbatools/assets/10188089/2fd0b7d5-8972-48bd-9bca-40bd971e645d)

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Invoke-Dbaquery -sqlinstance sql01 -database Master -query 'Select GETDATE()' 
![17195096909353759074452397020006](https://github.com/dataplat/dbatools/assets/10188089/038035db-ffc9-46b0-9e37-bd7fc86d5037)

### Please confirm that you are running the most recent version of dbatools

![17195097499623298296969072626451](https://github.com/dataplat/dbatools/assets/10188089/f3fe77ea-fbfa-4b66-8f25-eac594cefb5e)

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

![17195097814634483871519832405512](https://github.com/dataplat/dbatools/assets/10188089/8b20752c-7418-4078-a06f-d2e454d9abdd)

### SQL Server Edition and Build number

![17195098821225744500205946047590](https://github.com/dataplat/dbatools/assets/10188089/1116fbfb-8750-4115-b449-935016373dc2)

### .NET Framework Version

![17195100335932122202169534088502](https://github.com/dataplat/dbatools/assets/10188089/553f487c-9b35-461a-a593-f6ae4dfd60a9)

**Comment by andreasjordan** [comment] 2024-06-27 17:43
But you connect to the server by SQL Server Management Studio from this computer?

**Comment by jyoukhanis** [comment] 2024-06-27 17:51
Yes I can.

**Comment by andreasjordan** [comment] 2024-06-27 18:16
Maybe Test-DbaConnection can give you more information where the problem is.

**Comment by wsmelton** [comment] 2024-06-29 23:27
Please remove any old versions from the device prior to v2 and let us know if you continue to see errors.

**Comment by mattcargile** [comment] 2024-08-02 19:00
Looks like you might have _Cisco AnyConnect_ . I assume you were connected when you attempted the `Invoke-DbaQuery`? Additionally, I would try adding the domain suffix on the host name.

**Comment by potatoqualitee** [comment] 2024-08-22 07:15
also try with Connect-DbaInstance and use -Verbose. let us know what that says. Usually the network path not being found is when people type in the wrong address but I triple checked and its the same server. You can also try connecting to the fully qualified domain name (sql01 vs sql01.ad.local)

**Comment by niphlod** [comment] 2024-09-25 20:47
@jyoukhanis : I'm closing this as there are no replies from your side. Feel free to reopen in case you need more help

**Closed by niphlod** 2024-09-25 20:47 UTC
Labels: bugs life, pending OP feedback
