### ISSUE TITLE
Add SQL 2022 to  Set-DbaDBCompatibility.ps1

### ISSUE THREAD

**Issue by IIJohnnyRingoII** [dataplat/dbatools#8762] opened 2023-02-15 17:09 UTC
### Summarize Functionality

Add SQL 2022 to  Set-DbaDBCompatibility.ps1

![image](https://user-images.githubusercontent.com/124267558/219101780-59cdfedf-d7f8-4eaa-8b5c-53c3bb8a0ae2.png)

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by wsmelton** [comment] 2023-02-15 19:03
Maintainer note: All of this needs to be removed from the module and replaced with the enum object in SMO.

**Comment by SteveKnowless** [comment] 2023-02-17 16:41
Seeing this issue as well when upgrading severs to SQL2022. Thanks for the hard work

**Comment by wsmelton** [comment] 2023-02-27 20:01
Duplicate of #8718

**Closed by wsmelton** 2023-02-27 20:01 UTC
Labels: feature
