### ISSUE TITLE
New-DbaAgentSchedule not reflecting JobCount when adding to existing job

### ISSUE THREAD

**Issue by lowlydba** [dataplat/dbatools#8933] opened 2023-05-29 16:45 UTC
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When specifying a Job name in New-DbaAgentSchedule, the JobCount value does not properly reflect the number of jobs the schedule is attached to. The jobschedule object just needs a refresh to properly reflect the change.

### Steps to Reproduce

```powershell
# Example 1
$server = Connect-DbaInstance -SqlInstance localhost
$j = New-DbaAgentJob -SqlInstance $server -Job 'test4'
$x = New-DbaAgentSchedule -SqlInstance $server -Force -Schedule 'test_sched4' -Job 'test4'

# Incorrect count 
$x.JobCount

# Correct count
$x.Refresh()
$x.JobCount

# Example 2

$SqlInstance = 'localhost'
$j = New-DbaAgentJob -SqlInstance $SqlInstance -Job 'test4'
$x = New-DbaAgentSchedule -SqlInstance $SqlInstance -Force -Schedule 'test_sched4' -Job 'test4'

$x.JobCount

$x.Refresh()
$x.JobCount

```

### Please confirm that you are running the most recent version of dbatools

Yes, 2.0.3

### Other details or mentions

Introduced in v2.0.2

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

N/A

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by wsmelton** [comment] 2023-05-29 17:51
This is by design (of SMO) and a byproduct of using your own connection. SMO create methods do not refresh the object they return. We do not in most (we may have made an exception in one or two I recall) of our New commands and shouldn't for performance reasons. 

If you want a fresh count call the Get function for that object type.

**Comment by wsmelton** [comment] 2023-05-29 18:13
We also already do a refresh in this command in two places:

https://github.com/dataplat/dbatools/blob/a0d3acc4f3913925ec0288c276ad1526397a231d/public/New-DbaAgentSchedule.ps1#L527-L529

**Comment by lowlydba** [comment] 2023-05-29 18:23
> Have you tried running your same test without using Connect command?

Yes, that is the broken behavior. I added a second example without Connect. 

> This is by design (of SMO) and a byproduct of using your own connection. SMO create methods do not refresh the object they return. We do not in most (we may have made an exception in one or two I recall) of our New commands and shouldn't for performance reasons. You created one object, only function of New is to create that object and not to go fetch the current count on the server(s), that would be a huge performance hit for automation if you do that in every New command.
> 
> If you want a fresh count call the Get function for that object type.

So you're saying its by design the function returns stale metadata that doesn't reflect the operation it just performed? Not sure I can agree with that take.

**Comment by wsmelton** [comment] 2023-05-29 18:29
If this is a regression then the change that broken it should be addressed, not just throwing in another `Refresh()` method.

Based on history this block changed with @potatoqualitee adding auto-scheduling functionality: #8911

**Comment by lowlydba** [comment] 2023-05-29 18:34
Great! I'm going to bow out since I don't seem to have enough context to come up with a satisfactory solution. I'll look about doing some localized workarounds in the mean time until a fix is released.

**Comment by wsmelton** [comment] 2023-05-29 18:39
There some other failure messages that need to be fixed in this command as well. I'll see if I can get that fixed to figure out why the count refresh is not working anymore.

**Comment by wsmelton** [comment] 2023-05-29 19:40
It seems the test for this command has been broken but not sure for how long. Adding `EnableException` causes it to actually fail to create the job properly.
https://ci.appveyor.com/project/dataplat/dbatools/builds/47168479/job/l891ytsel6tokr18

![image](https://github.com/dataplat/dbatools/assets/11204251/7395881f-ae15-48e6-b077-740a5e98b980)

Not sure if this causes issues with the integration test directly as I think this failure is on the job step creation, not the job itself.

**Closed** 2023-05-30 07:49 UTC
Labels: pending team feedback
